import type {Color,Key,ProjectDocument,Vec3} from './types';
export class ProjectError extends Error{}
type Mat=number[]; const I=():Mat=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];
const mul=(a:Mat,b:Mat)=>a.map((_,i)=>{const r=i>>2,c=i&3;return a[r*4]*b[c]+a[r*4+1]*b[c+4]+a[r*4+2]*b[c+8]+a[r*4+3]*b[c+12]});
const mv=(m:Mat,v:number[])=>[m[0]*v[0]+m[1]*v[1]+m[2]*v[2]+m[3],m[4]*v[0]+m[5]*v[1]+m[6]*v[2]+m[7],m[8]*v[0]+m[9]*v[1]+m[10]*v[2]+m[11]];
const euler=(d:Vec3):Mat=>{const [x,y,z]=d.map(v=>v*Math.PI/180),cx=Math.cos(x),sx=Math.sin(x),cy=Math.cos(y),sy=Math.sin(y),cz=Math.cos(z),sz=Math.sin(z);return [cy*cz,-cy*sz,sy,0,cx*sz+sx*sy*cz,cx*cz-sx*sy*sz,-sx*cy,0,sx*sz-cx*sy*cz,sx*cz+cx*sy*sz,cx*cy,0,0,0,0,1]};
const transform=(r:Vec3|undefined=[0,0,0],t:Vec3|undefined=[0,0,0])=>{r=r||[0,0,0];t=t||[0,0,0];const m=euler(r);m[3]=t[0];m[7]=t[1];m[11]=t[2];return m};
const norm=(v:number[])=>{const n=Math.hypot(...v);return n>1e-9?v.map(x=>x/n):v};
export const normalizeAngle=(v:number)=>{const x=(v+180)%360;const y=(x<0?x+360:x)-180;return Math.abs(y)<1e-10?0:y};
export function solveTwoBone(root:Vec3,target:Vec3,l1:number,l2:number,pole:Vec3):[Vec3,Vec3]{const sub=(a:number[],b:number[])=>a.map((x,i)=>x-b[i]),add=(a:number[],b:number[])=>a.map((x,i)=>x+b[i]),dot=(a:number[],b:number[])=>a.reduce((n,x,i)=>n+x*b[i],0),scale=(a:number[],s:number)=>a.map(x=>x*s);const delta=sub(target,root),raw=Math.hypot(...delta),dir=raw>1e-9?norm(delta):[0,-1,0],dist=Math.max(Math.abs(l1-l2)+1e-6,Math.min(l1+l2-1e-6,raw));let bend=sub(pole,scale(dir,dot(pole,dir)));if(Math.hypot(...bend)<1e-6)bend=[dir[1],-dir[0],0];bend=norm(bend);const angle=Math.acos(Math.max(-1,Math.min(1,(l1*l1+dist*dist-l2*l2)/(2*l1*dist))));return[add(root,scale(add(scale(dir,Math.cos(angle)),scale(bend,Math.sin(angle))),l1)) as Vec3,add(root,scale(dir,dist)) as Vec3]}
const inverseRigid=(m:Mat):Mat=>[m[0],m[4],m[8],-(m[0]*m[3]+m[4]*m[7]+m[8]*m[11]),m[1],m[5],m[9],-(m[1]*m[3]+m[5]*m[7]+m[9]*m[11]),m[2],m[6],m[10],-(m[2]*m[3]+m[6]*m[7]+m[10]*m[11]),0,0,0,1];
const eulerFrom=(m:Mat):Vec3=>{const y=Math.asin(Math.max(-1,Math.min(1,m[2]))),cy=Math.cos(y),x=Math.abs(cy)>1e-7?Math.atan2(-m[6],m[10]):Math.atan2(m[9],m[5]),z=Math.abs(cy)>1e-7?Math.atan2(-m[1],m[0]):0;return[x,y,z].map(v=>normalizeAngle(v*180/Math.PI)) as Vec3};
export function reparent(d:ProjectDocument,name:string,parent:string|null){validateProject(d);if(!d.rig.bones[name])throw new ProjectError(`unknown bone '${name}'`);let cursor=parent;while(cursor){if(cursor===name)throw new ProjectError('reparent would create a parent cycle');cursor=d.rig.bones[cursor]?.parent||null}const world=pose(d),local=parent?mul(inverseRigid(world[parent]),world[name]):world[name],out=structuredClone(d),b=out.rig.bones[name];if(parent)b.parent=parent;else delete b.parent;b.translation=[local[3],local[7],local[11]];b.rotation=eulerFrom(local);validateProject(out);return out}
const rows=(s:unknown,label:string)=>{if(typeof s!=='string')throw new ProjectError(`${label} must be a multiline string`);const r=s.replace(/^\n|\n$/g,'').split('\n');if(!r.length||!r[0])throw new ProjectError(`${label} cannot be empty`);if(r.some(x=>x.length!==r[0].length))throw new ProjectError(`${label} has ragged rows`);return r};
const vec=(v:unknown,l:string,n=3)=>{if(!Array.isArray(v)||v.length!==n||v.some(x=>typeof x!=='number'||!Number.isFinite(x)))throw new ProjectError(`${l} must be a ${n}-number list`);return v as number[]};
export function validateProject(d:ProjectDocument){if(!d||typeof d!=='object')throw new ProjectError('project root must be a mapping');if(!d.palette||!Object.keys(d.palette).length)throw new ProjectError('palette must be a non-empty mapping');for(const [k,c] of Object.entries(d.palette)){if(k.length!==1||k==='.')throw new ProjectError("palette keys must be single characters other than '.'");color(c,`palette.${k}`)}if(!d.parts||!Object.keys(d.parts).length)throw new ProjectError('parts must be a non-empty mapping');for(const [n,p] of Object.entries(d.parts)){const f=rows(p.front,`parts.${n}.front`),b=rows(p.back,`parts.${n}.back`),s=rows(p.side,`parts.${n}.side`);for(const [vn,g] of [['front',f],['back',b],['side',s]] as const)g.forEach((r,y)=>[...r].forEach((ch,x)=>{if(ch!=='.'&&!d.palette[ch])throw new ProjectError(`parts.${n}.${vn} uses unknown palette character '${ch}' at row ${y+1}, column ${x+1}`)}));if(f.length!==b.length||f[0].length!==b[0].length)throw new ProjectError(`parts.${n}: front and back views must have equal dimensions`);if(f.length!==s.length)throw new ProjectError(`parts.${n}: front, back, and side views must have equal heights`);f.forEach((r,y)=>[...r].forEach((ch,x)=>{if((ch==='.')!==(b[y][x]==='.'))throw new ProjectError(`parts.${n}: front/back silhouettes differ at row ${y+1}, column ${x+1}`)}));if(p.pivot)vec(p.pivot,`parts.${n}.pivot`)}
 const bones=d.rig?.bones;if(!bones||!Object.keys(bones).length)throw new ProjectError('rig.bones must be a non-empty mapping');const visiting=new Set<string>(),done=new Set<string>();const visit=(n:string)=>{if(visiting.has(n))throw new ProjectError(`rig has a parent cycle involving '${n}'`);if(done.has(n))return;visiting.add(n);const b=bones[n];if(b.parent){if(!bones[b.parent])throw new ProjectError(`bone '${n}' references missing parent '${b.parent}'`);visit(b.parent)}if(b.part&&!d.parts[b.part])throw new ProjectError(`rig.bones.${n} references missing part '${b.part}'`);visiting.delete(n);done.add(n)};Object.keys(bones).forEach(visit);
 if(!d.animations||!Object.keys(d.animations).length)throw new ProjectError('animations must be a non-empty mapping');for(const [n,c] of Object.entries(d.animations)){if(!Number.isInteger(c.frames)||c.frames<1)throw new ProjectError(`animations.${n}.frames must be a positive integer`);if(!(c.fps>0))throw new ProjectError(`animations.${n}.fps must be positive`);for(const b of Object.keys(c.bones||{}))if(!bones[b])throw new ProjectError(`animations.${n}.bones references invalid bone '${b}'`);for(const q of Object.keys(c.ik||{}))if(!d.rig.ik_chains?.[q])throw new ProjectError(`animations.${n}.ik references invalid chain '${q}'`)}const ex=d.export||{},an=ex.animations||Object.keys(d.animations);if(!an.length)throw new ProjectError('export.animations must be a non-empty animation-name list');an.forEach(n=>{if(!d.animations[n])throw new ProjectError(`export.animations references missing animation '${n}'`)});return d}
export function color(v:Color,label='color'):[number,number,number,number]{if(typeof v==='string'){if(!/^#[0-9a-f]{6}([0-9a-f]{2})?$/i.test(v))throw new ProjectError(`${label} must be #RRGGBB, #RRGGBBAA, or an RGB(A) list`);const a=[1,3,5,7].filter(i=>i<v.length).map(i=>parseInt(v.slice(i,i+2),16));return [a[0],a[1],a[2],a[3]??255]}if(!Array.isArray(v)||![3,4].includes(v.length)||v.some(x=>!Number.isInteger(x)||x<0||x>255))throw new ProjectError(`${label} channels must be integers from 0 to 255`);return [v[0],v[1],v[2],v[3]??255]}
const sample=(ks:Key<any>[]|undefined,f:number,loop:boolean,frames:number)=>{if(!ks?.length)return null;const exact=ks.find(k=>k.frame===f);if(exact)return exact.value;let l=[...ks].reverse().find(k=>k.frame<f),r=ks.find(k=>k.frame>f),pos=f;if(!l||!r){if(!loop||ks.length<2)return (l||r)!.value;if(l)r={...ks[0],frame:ks[0].frame+frames};else{l={...ks.at(-1)!,frame:ks.at(-1)!.frame-frames};r=ks[0]}}if(l!.interpolation==='step')return l!.value;let t=(pos-l!.frame)/(r!.frame-l!.frame);if(l!.interpolation==='smooth')t=t*t*(3-2*t);const a=l!.value,b=r!.value;return Array.isArray(a)?a.map((x:number,i:number)=>x*(1-t)+b[i]*t):a*(1-t)+b*t};
export function pose(d:ProjectDocument,clipName?:string,frame=0){validateProject(d);const out:Record<string,Mat>={},pending=new Set(Object.keys(d.rig.bones)),clip=clipName?d.animations[clipName]:undefined;while(pending.size)for(const n of [...pending]){const b=d.rig.bones[n];if(b.parent&&!out[b.parent])continue;const tr=clip?.bones?.[n],t=sample(tr?.translation,frame,clip.loop!==false,clip.frames) as Vec3|null,r=sample(tr?.rotation,frame,clip.loop!==false,clip.frames) as Vec3|null;const bt=b.translation||[0,0,0],local=transform([(b.rotation?.[0]||0)+(r?.[0]||0),(b.rotation?.[1]||0)+(r?.[1]||0),(b.rotation?.[2]||0)+(r?.[2]||0)],[bt[0]+(t?.[0]||0),bt[1]+(t?.[1]||0),bt[2]+(t?.[2]||0)]);out[n]=b.parent?mul(out[b.parent],local):local;pending.delete(n)}return out}
function voxels(d:ProjectDocument,p:string){const q=d.parts[p],f=rows(q.front,''),b=rows(q.back,''),s=rows(q.side,''),h=f.length,w=f[0].length,zs=s[0].length,piv=q.pivot||[(w-1)/2,0,(zs-1)/2] as Vec3,res:any[]=[];for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(f[y][x]!=='.')for(let z=0;z<zs;z++)if(s[y][z]!=='.'){const rx=x-(w-1)/2,rz=z-(zs-1)/2,ch=Math.abs(rz/Math.max((zs-1)/2,.5))>=Math.abs(rx/Math.max((w-1)/2,.5))?(rz>=0?f[y][x]:b[y][x]):s[y][z];res.push({p:[x-piv[0],h-1-y-piv[1],z-piv[2]],c:color(d.palette[ch]),n:[rx,(h-1-y)-(h-1)/2,rz]})}return res}
export function render(d:ProjectDocument,clip?:string,frame=0,yaw=0,part?:string,size?:number){const ex=d.export||{},w=size||ex.size?.[0]||96,h=size||ex.size?.[1]||96,scale=size?Math.max(1,Math.min(16,Math.floor((size-40)/8))):ex.scale||3,origin=size?[w/2,h/2]:ex.origin||[w/2,h-8],canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d')!,im=ctx.createImageData(w,h),bg=color(ex.background||[0,0,0,0]);for(let i=0;i<im.data.length;i+=4)im.data.set(bg,i);const ps=pose(d,clip,frame),all:any[]=[];const yawR=yaw*Math.PI/180,c=Math.cos(yawR),s=Math.sin(yawR);for(const [bn,b] of Object.entries(d.rig.bones)){if(part&&b.part!==part)continue;if(!b.part)continue;const at=mul(ps[bn],transform(b.attachment?.rotation,b.attachment?.translation));for(const v of voxels(d,b.part)){const p=mv(at,v.p),x=c*p[0]+s*p[2],z=-s*p[0]+c*p[2];all.push({x:origin[0]+x*scale,y:origin[1]-p[1]*scale,z,c:v.c})}}all.sort((a,b)=>a.z-b.z);for(const v of all){const x0=Math.floor(v.x-scale/2),y0=Math.floor(v.y-scale/2);for(let y=y0;y<=y0+scale;y++)for(let x=x0;x<=x0+scale;x++)if(x>=0&&y>=0&&x<w&&y<h){const i=(y*w+x)*4;im.data.set(v.c,i)}}ctx.putImageData(im,0,0);return canvas}
export function overlay(d:ProjectDocument,clip:string|undefined,frame:number,yaw:number){const p=pose(d,clip,frame),ex=d.export||{},o=ex.origin||[48,88],sc=ex.scale||3,a=yaw*Math.PI/180,c=Math.cos(a),s=Math.sin(a);return{width:ex.size?.[0]||96,height:ex.size?.[1]||96,bones:Object.keys(d.rig.bones).map(n=>{const m=p[n],x=c*m[3]+s*m[11],z=-s*m[3]+c*m[11];return{name:n,parent:d.rig.bones[n].parent||null,x:o[0]+x*sc,y:o[1]-m[7]*sc,depth:z}}),chains:[]}}
export function metadata(d:ProjectDocument){const ex=d.export||{},names=ex.animations||Object.keys(d.animations),dirs=ex.directions||[0,45,90,135,180,225,270,315],w=ex.size?.[0]||96,h=ex.size?.[1]||96,cols=Math.max(...names.map(n=>d.animations[n].frames));let row=0;const animations:any={};for(const n of names){const c=d.animations[n],cm:any={fps:c.fps,frame_duration_ms:1000/c.fps,loop:c.loop!==false,directions:[]};for(const angle of dirs){cm.directions.push({angle,frames:Array.from({length:c.frames},(_,i)=>({index:i,rect:{x:i*w,y:row*h,w,h},pivot:{x:i*w+(ex.origin?.[0]||w/2),y:row*h+(ex.origin?.[1]||h-8)}}))});row++}animations[n]=cm}return{image:`${ex.name||'sprite'}.png`,size:{w:cols*w,h:row*h},frame_size:{w,h},coordinate_system:{atlas_origin:'top-left',world:'+X right, +Y up, +Z forward'},animations}}
